config/routes.rb
Rails.application.routes.draw do
  resources :hashtags
  root 'users#index'

  resources :users
  resources :sessions, only: %i[new create destroy]
  resources :questions, except: %i[show new index]
  resources :hashtags, only: [:show]

  get 'sign_up' => 'users#new'
  get 'log_out' => 'sessions#destroy'
  get 'log_in' => 'sessions#new'
end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :user
  belongs_to :author,
             class_name: 'User',
             optional: true

  has_many :hashtag_questions, dependent: :destroy
  has_many :hashtags, through: :hashtag_questions

  validates :text, presence: true, length: { maximum: 255 }

  after_commit :delete_hashtag, on: %i[destroy update]
  after_commit :create_hashtag, on: %i[create update]

  def create_hashtag
    find_hashtags.each do |t|
      # находим хештег в БД или создаем новый
      tag = Hashtag.find_or_create_by(text: t)
      # связываем хештег с вопросом
      hashtags << tag
    end
  end

  def delete_hashtag
    # ищем по запросу все хештеги, у которых нет связей с вопросами и удаляем их
    Hashtag.left_joins(:hashtag_questions).
      where(hashtag_questions: { hashtag_id: nil }).destroy_all
  end

  private

  # метод для поиска хештегов в тексте вопроса и его ответе
  def find_hashtags
    "#{text} #{answer}".downcase.scan(Hashtag::TAG_REGEX).uniq
  end
end

app/controllers/questions_controller.rb
# (c) goodprogrammer.ru
#
# Контроллер, управляющий вопросами. Действия:
#
# 1. Редактирует вопрос
# 2. Создает вопрос
# 3. Удаляет вопрос
#
class QuestionsController < ApplicationController
  # Инициализируем объект вопрос для экшенов кроме :edit, :update, :destroy
  before_action :load_question, only: %i[edit update destroy]

  # Проверяем имеет ли юзер доступ к экшену для всей дествий, кроме задавания
  # вопроса, это действие может вызвать даже неавторизованный пользователь.
  before_action :authorize_user, except: [:create]

  # Действие edit будет отзываться по адресу /questions/:id/edit, например,
  # /questions/1/edit
  #
  # Перед этим действием сработает before_action :load_questions и в переменной
  # @question у нас будет лежать вопрос с нужным id равным params[:id].
  def edit; end

  # Действие create будет отзываться при POST-запросе по адресу /questions из
  # формы нового вопроса, которая находится в шаблоне на странице
  # /questions/edit
  def create
    @question = Question.new(question_params)
    @question.author = current_user

    if @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос задан'
    else
      render :edit
    end
  end

  # Действие update будет отзываться при PUT-запросе из формы редактирования
  # вопроса, которая находится по адресу /questions/:id, например, /questions/1
  #
  # Перед этим действием сработает before_action :load_questions и в переменной
  # @question у нас будет лежать вопрос с нужным id равным params[:id].
  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Вопрос сохранен'
    else
      render :edit
    end
  end

  # Действие destroy будет отзываться при DELETE-запросе со страницы
  # пользователя, которая находится по адресу /users/:id/show.
  #
  # Перед этим действием сработает before_action :load_questions и в переменной
  # @question у нас будет лежать вопрос с нужным id равным params[:id].
  def destroy
    # Перед тем, как удалять вопрос, сохраним пользователя, чтобы знать, куда
    # редиректить после удаления.
    user = @question.user

    # Удаляем вопрос
    @question.destroy

    # Отправляем пользователя на страницу адресата вопроса с сообщением
    redirect_to user_path(user), notice: 'Вопрос удален :('
  end

  private

  # Если загруженный из базы вопрос не пренадлежит и текущему залогиненному
  # пользователю — посылаем его с помощью описанного в контроллере
  # ApplicationController метода reject_user.
  def authorize_user
    reject_user unless @question.user == current_user
  end

  # Загружаем из базы запрошенный вопрос, находя его по params[:id].
  def load_question
    @question = Question.find(params[:id])
  end

  # Явно задаем список разрешенных параметров для модели Question. Мы говорим,
  # что у хэша params должен быть ключ :question. Значением этого ключа может
  # быть хэш с ключами: :user_id и :text. Другие ключи будут отброшены.
  def question_params
    # Защита от уязвимости: если текущий пользователь — адресат вопроса,
    # он может менять ответы на вопрос, ему доступно также поле :answer.
    if current_user.present? &&
       params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer)
    else
      params.require(:question).permit(:user_id, :text)
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  
  def questions_amount(number, vopros, voprosa, voprosov)
    ostatok100 = number % 100
    if ostatok100 >= 11 && ostatok100 <= 14
      return voprosov
    end
    ostatok = number % 10
    if ostatok == 1
      return vopros
    end
    if (2..4).include?(ostatok)
      return voprosa
    end
    voprosov
  end
end

app/views/questions/_form.html.erb
<%# Форма для создания/правки вопроса %>
<div class="form">
  <%# Форма для объекта @question %>
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div class="form-errors">
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li class="form-error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%# Скрытое поле — айдишник юзера, кому задается вопрос %>
    <%= f.hidden_field :user_id %>

    <div class="form-field">
      <%= f.label :text, 'Вопрос', class: 'form-label' %>
      <%= f.text_area :text, class: 'form-textarea' %>
    </div>

    <%# Простая авторизация - может ли текущий юзер править вопрос? %>
    <% if current_user.present? && current_user == @question.user %>
      <div class="form-field">
        <%= f.label :answer, 'Ответ', class: 'form-label' %>
        <%= f.text_area :answer, class: 'form-textarea' %>
      </div>
    <% end %>

    <div class="form-action buffer-both">
      <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      или
      <%= link_to "вернуться", user_path(@question.user) %>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<%# Это фрагмет (паршал, partial) для вывода вопроса. В нем определена %>
<%# локальная переменная question, в которую при вызове будет передан %>
<%# как в метод ruby объект после ключа (object: @question) %>

<div class="question">
  <div class="question-content">
    <%# Текст вопроса %>
    <div class="question-text text-lead">
      <%= question.text %>
    </div>

    <%# Текст ответа, если он есть %>
    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= question.answer %>
      </div>
    <% end %>

    <div class="question-date">
      <%= l(question.created_at, format: :short) %>
    </div>
    <%= link_to("@#{question.author.username}",
                user_path(question.author), class: 'author-link') if question.author.present? %>
    <div class="container">
      <% if question.hashtags.any? %>
        <% question.hashtags.uniq.each do |tag| %>
          <%= link_to tag.text, hashtag_path(tag), class: 'tag-link' %>
        <% end %>
      <% end %>
    </div>
  </div>

  <%# Если адресат вопроса — текущий пользователь, он может редактировать вопрос %>
  <%# и отвечать на него %>
  <% if question.user == current_user %>
    <%# Определяем какая будет иконка, если у вопроса нет ответа, то иконка %>
    <%# овтета на письмо, иначе — карандашик %>
    <% edit_icon = question.answer.blank? ? 'reply' : 'pencil' %>

    <div class="question-actions">
      <%= link_to fa_icon(edit_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question),
                  method: :delete, data: {confirm: 'Точно удалить вопрос?'} %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<%# Страница редактирования вопроса %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>

  <div class="column-1-2">
    <%# Подключаем паршиал app/views/questions/_form.html.erb %>
    <%= render 'form' %>
  </div>
</div>