config/routes.rb
Rails.application.routes.draw do
  resources :hashtags
  root 'users#index'

  resources :users
  resources :sessions, only: %i[new create destroy]
  resources :questions, except: %i[show new index]
  resources :hashtags, only: [:show]

  get 'sign_up' => 'users#new'
  get 'log_out' => 'sessions#destroy'
  get 'log_in' => 'sessions#new'
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  # Параметры работы для модуля шифрования паролей
  ITERATIONS = 20_000
  DIGEST = OpenSSL::Digest::SHA256.new
  EMAIL_REGEX = URI::MailTo::EMAIL_REGEXP
  USERNAME_REGEX = /\A[a-zA-Z0-9_]+\z/
  COLOR_REGEX = /\A#(?:[0-9a-fA-F]{3}){1,2}\z/

  NAME_LENGTH = 40

  attr_accessor :password

  has_many :questions

  validates :email,
            presence: true,
            uniqueness: true,
            format: { with: EMAIL_REGEX }

  validates :username,
            presence: true,
            uniqueness: true,
            format: { with: USERNAME_REGEX }

  validates :name,
            presence: true,
            length: { maximum: NAME_LENGTH }

  validates :color,
            presence: true,
            format: { with: COLOR_REGEX }

  before_validation :username_downcase, :email_downcase
  before_save :encrypt_password

  validates :password, presence: true, on: :create
  validates_confirmation_of :password

  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email)

    return nil unless user.present?

    hashed_password = User.hash_to_string(
      OpenSSL::PKCS5.pbkdf2_hmac(
        password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST
      )
    )
    return user if user.password_hash == hashed_password
    nil
  end

  private

  def encrypt_password
    if password.present?
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))

      self.password_hash = User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(
          password, password_salt, ITERATIONS, DIGEST.length, DIGEST
        )
      )
    end
  end

  def username_downcase
    username&.downcase!
  end

  def email_downcase
    email&.downcase!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: %i[index create new]
  # Проверяем имеет ли юзер доступ к экшену, делаем это для всех действий, кроме
  # :index, :new, :create, :show — к этим действиям есть доступ у всех, даже у
  # тех, у кого вообще нет аккаунта на нашем сайте.
  before_action :authorize_user, except: %i[index new create show]

  def index
    @users = User.all
    @hashtags = Hashtag.order(:text)
  end

  def edit; end

  def new
    redirect_to root_path, alert: 'Вы уже залогинены' if current_user.present?

    @user = User.new
  end

  def create
    redirect_to root_path, alert: 'Вы уже залогинены' if current_user.present?

    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Пользователь успешно зарегистрирован'
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Данные обновлены'
    else
      render 'edit'
    end
  end

  def show
    @questions = @user.questions.order(created_at: :desc)
    @new_question = @user.questions.build
    @questions_amount = @questions.length
    @answers_amount = @questions.where.not(answer: nil).length
    @unanswered_amount = @questions_amount - @answers_amount
  end

  def destroy
    @user.destroy

    redirect_to root_path, notice: 'Пользователь удален :('
  end

  private

  def authorize_user
    reject_user unless @user == current_user
  end

  def load_user
    @user ||= User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :name, :username, :avatar_url, :color)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%# Страница редактирования пользователя %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Править профиль</h1>

  <div class="column-1-2">
    <%# С помощью специального хелпера form_for мы делаем тег <form ...> %>
    <%# с нужными аттрибутами, после этого в переменной f будет специальный %>
    <%# объект (form builder object), вызывая методы которого мы можем %>
    <%# создавать теги для нужных нам полей формы. %>
    <%= form_for(@user) do |f| %>
      <%# Вывод ошибок валидации пользователя, если есть. Ошибки содержатся %>
      <%# в поле errors модели (в нашем случае @users). %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%# С помощью методов label и text_field у объекта f мы создаем теги %>
      <%# <label ... > и <input type="text" ... > с нужными атрибуами %>
      <div class="form-field">
        <%= f.label :username, class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <%# Поступаем аналогично для других полей %>
      <div class="form-field">
        <%= f.label 'Ваше имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'URL вашей аватарки', class: 'form-label' %>
        <%= f.text_field :avatar_url, class: 'form-text-field' %>
      </div>

      <div class="form-group">
        <%= f.label 'Цвет фона блока с аватаркой', class: 'form-label' %>
        <select <%= f.color_field :color %>>
          <option value="#005a55">Default</option>
          <option value="#7bd148">Green</option>
          <option value="#5484ed">Bold blue</option>
          <option value="#a4bdfc">Blue</option>
          <option value="#46d6db">Turquoise</option>
          <option value="#7ae7bf">Light green</option>
          <option value="#51b749">Bold green</option>
          <option value="#fbd75b">Yellow</option>
          <option value="#ffb878">Orange</option>
          <option value="#ff887c">Red</option>
          <option value="#dc2127">Bold red</option>
          <option value="#dbadff">Purple</option>
          <option value="#e1e1e1">Gray</option>
        </select>
      </div>

      <div class="buffer-top-large buffer-bottom">
        Если не хотите менять пароль — оставьте эти поля пустыми!
      </div>

      <div class="form-field">
        <%= f.label :password, class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action buffer-top">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
        <%= link_to 'Удалить аккаунт', user_path(@user), class: 'button button-red button-small',
                    method: :delete, data: {confirm: 'Вы действительно хотите удалить свой аккаунт?'} %>
      </div>
    <% end %>

    <%# Подробнее про помощники для создания форм: %>
    <%# http://guides.rubyonrails.org/form_helpers.html %>
  </div>
</div>

<script type='text/javascript'>
    $(function (){
        $('#user_color').simplecolorpicker();
    });
</script>

app/views/users/index.html.erb
<%# Этот шаблон отрисуется, когда пользователь захочет посмотреть список пользователей %>
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <%# Этот код выводит каждого пользователя в цикле %>
  <% @users.each do |user| %>
      <div class="users-list-item">
        <div class="user-image-div user-image-div-small">
          <%# Пользуемся аж тремя хелперами %>
          <%# link_to — генерирует ссылку %>
          <%# image_tag — генерирует картинку %>
          <%# user_avatar — достает из пользователя ссылку на картинку или подставляет дефолтную %>
          <%# Хелпер user_path(user) возвращает относительный путь %>
          <%# страницы пользователя, например /users/1 %>
          <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
        </div>
      </div>
  <% end %>

  <% if @hashtags.any? %>
    <div class='buffer-top'>
      <% @hashtags.each do |tag| %>
        <%= link_to tag.text, hashtag_path(tag), class: 'tag-link' %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%# Страница для регистрации нового пользователя. %>

<%# Обратите внимание, что она очень похожа на страницу редактирования юзера, %>
<%# что позволяет в подобных случаях использовать один и тот же паршиал form %>
<%# в обоих страницах. %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="column-1-2">
    <%# С помощью специального хелпера form_for мы делаем тег <form ...> %>
    <%# с нужными аттрибутами, после этого в переменной f будет специальный %>
    <%# объект (form builder object), вызывая методы которого мы можем %>
    <%# создавать теги для нужных нам полей формы. %>
    <%= form_for @user do |f| %>
      <%# Вывод ошибок валидации пользователя, если есть. Ошибки содержатся %>
      <%# в поле errors модели (в нашем случае @users). %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% @user.errors.full_messages.each { |message| %>
            <li class="form-error-message"><%=  message  %></li>
            <%  } %>
          </ul>
        </div>
      <% end %>

      <%# С помощью методов label и text_field у объекта f мы создаем теги %>
      <%# <label ... > и <input type="text" ... > с нужными атрибуами %>
      <div class="form-field">
        <%= f.label :email, 'Логин (email)', class: 'form-label' %>
        <%= f.text_field :email, class: 'form-text-field' %>
      </div>

      <%# Поступаем аналогично для других полей %>
      <div class="form-field">
        <%= f.label :username, 'Никнейм', class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, 'Имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password, 'Пароль', class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'Цвет фона блока с аватаркой', class: 'form-label' %>
        <select <%= f.color_field :color %>>
          <option value="#005a55">Default</option>
          <option value="#7bd148">Green</option>
          <option value="#5484ed">Bold blue</option>
          <option value="#a4bdfc">Blue</option>
          <option value="#46d6db">Turquoise</option>
          <option value="#7ae7bf">Light green</option>
          <option value="#51b749">Bold green</option>
          <option value="#fbd75b">Yellow</option>
          <option value="#ffb878">Orange</option>
          <option value="#ff887c">Red</option>
          <option value="#dc2127">Bold red</option>
          <option value="#dbadff">Purple</option>
          <option value="#e1e1e1">Gray</option>
        </select>
      </div>

      <div class="form-action">
        <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
      </div>
    <% end %>

    <%# Подробнее про помощники для создания форм: %>
    <%# http://guides.rubyonrails.org/form_helpers.html %>
  </div>
</div>

<script type='text/javascript'>
    $(function (){
        $('#user_color').simplecolorpicker();
    });
</script>

app/views/users/show.html.erb
<div class="user-header text-center" style="background-color: <%= @user.color %>">
  <h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>

  <%# Добавляем ссылку для редактирования пользователя, которая ведет на %>
  <%# страницу /users/:id/edit %>
  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>

  <div class="user-ask-button container text-center">
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>
</div>

<div class="question question-content question-text text-lead">
  <p>У вас всего <%= @questions_amount %> <%= questions_amount(@questions_amount, 'вопрос', 'вопроса', 'вопросов') %></p>
  <p class="text-small">Вы ответили на <%= @answers_amount %> /
    <%= @unanswered_amount %> <%= questions_amount(@unanswered_amount, 'вопрос', 'вопроса', 'вопросов') %> без ответа</p>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <%= form_for @new_question do |f| %>
      <%= f.hidden_field :user_id %>
      <%= f.hidden_field :author_id, value: current_user.id if current_user.present? %>

      <div class="form-field">
        <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
        <%= f.text_area :text, class: 'form-textarea' %>
      </div>

      <div class="form-action">
        <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
      </div>
    <% end %>
  </div>
</div>

<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="questions-list">
      <% @questions.each do |question| %>
        <%# Мы рисуем здесь для кажого вопроса в списке вопросов фрагмент %>
        <%# (паршал), передавая в него текущий вопрос. Это очень похоже на %>
        <%# вызов метода в ruby. %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>