config/routes.rb
Rails.application.routes.draw do
  resources :hashtags
  root 'users#index'

  resources :users
  resources :sessions, only: %i[new create destroy]
  resources :questions, except: %i[show new index]
  resources :hashtags, only: [:show]

  get 'sign_up' => 'users#new'
  get 'log_out' => 'sessions#destroy'
  get 'log_in' => 'sessions#new'
end

app/views/layouts/application.html.erb
<%# Это общий шаблон для всех страниц нашего сайта. В него будут завернуты %>
<%# страницы нашего приложения. Здесь мы пропишем основную структуру наших %>
<%# html-страниц и укажем, куда вставлять шаблон отдельной вьюхи. %>
<!DOCTYPE html>
<html>
<%# Именно он определяет, что будет в теге head каждой нашей html-страницы %>
<head>
  <meta charset="UTF-8"/>
  <%# Именно здесь мы подключаем все стили и прописываем один (в рамках %>
  <%# обучения) тег title для всех страниц сайта %>
  <title>Хорошие вопросы</title>
  <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/le-frog/jquery-ui.min.css' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
  <div class="container">
    <div class="header-logo">
      <%# Ссылка на главную страницу сайта (root_path) %>
      <h1 class="header-title"><%= link_to "Хорошие вопросы", root_path %></h1>
    </div>
    <%# Выводим в хэдере информацию для логина/авторизации/регистрации %>
    <div class="header-nav">
      <%# Если есть текущий юзер (значит он залогинен) %>
      <% if current_user %>
        <%# Даем ссылки на его профиль и на логаут %>
        <%= link_to "@#{current_user.username}", user_path(current_user) %> |
        <%= link_to 'Выйти', log_out_path %>
      <% else %>
        <%# Если нету — ссылки на регистрацию и логин %>
        <%= link_to 'Зарегистрироваться', sign_up_path,
                    class: 'button button-light button-small' %>
        <%= link_to 'Войти', log_in_path,
                    class: 'button button-light button-small' %>
      <% end %>
    </div>
  </div>
</div>

<div class="content">
  <div class="container">
    <% if flash.any? %>
      <div class="content-wrapper buffer-both">
        <% flash.each do |name, message| %>
          <%= content_tag :div, message, class: "flash-#{name}" %>
        <% end %>
      </div>
    <% end %>
    <%# Вместо волшебной конструкции yield рельсы подставят то, что срендерит %>
    <%# шаблон для нужной нам страницы, например, users/show %>
    <%= yield %>
  </div>
</div>


</body>
</html>